routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PeopleController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\NoteController;
use App\Http\Controllers\BusinessController;
use App\Http\Controllers\WorkController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\PasswordController;
use App\Http\Controllers\ConversationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return view('welcome');
});

Route::get('/'                          , [HomeController::class, 'index'])->middleware('auth');
Route::get('/home'                      , [HomeController::class, 'index'])->middleware('auth');

Route::resource('people'                , PeopleController::class)->middleware('auth');
Route::resource('category'              , CategoryController::class)->middleware('auth');
Route::resource('note'                  , NoteController::class)->middleware('auth');
Route::resource('business'              , BusinessController::class)->middleware('auth');
Route::resource('work'                  , WorkController::class)->middleware('auth');
Route::resource('support'               , SupportController::class)->middleware('auth');
Route::resource('password'              , PasswordController::class)->middleware('auth');
Route::resource('conversation'          , ConversationController::class)->middleware('auth');
Route::get('conversation/search/{id}'   , [ConversationController::class, 'search'])->middleware('auth');

Route::post('search'                    , [HomeController::class, 'search'])->middleware('auth');

app/Models/Work.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Work extends Model
{
	protected $dates = ['date', 'expires'];

    public function business()
    {
        return $this->belongsTo('App\Models\Business');
    }

    public function user()
    {
    	return $this->belongsTo('App\Models\User');
    }
}

app/Http/Controllers/WorkController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Work;
use Auth;
use Carbon\Carbon;

class WorkController extends Controller
{
    private $path = "work.";

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view($this->path."index");
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->path."create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $work               = new Work();
        
        if ($request->date == null) 
            $date = Carbon::now();
        else
            $date = $request->date;

        $work->date         = $date;
        $work->description  = $request->description;
        $work->cost         = $request->cost;
        $work->gain         = $request->gain;
        $work->saved        = $request->saved;
        $work->expires      = $request->expires;
        $work->status       = $request->status;
        $work->business_id  = $request->business_id;
        $work->user_id      = Auth::user()->id;

        $work->save();

        return redirect('work');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $work = Work::find($id);

        return view($this->path."edit", compact('work'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $work               = Work::find($id);
        
        if ($request->date == null) 
            $date = Carbon::now();
        else
            $date = $request->date;

        $work->date         = $date;
        $work->description  = $request->description;
        $work->cost         = $request->cost;
        $work->gain         = $request->gain;
        $work->saved        = $request->saved;
        $work->expires      = $request->expires;
        $work->status       = $request->status;
        $work->business_id  = $request->business_id;
        $work->save();

        return redirect('work');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $work = Work::find($id);
        $work->delete();

        return back();
    }
}

resources/views/work/create.blade.php
@extends('layouts.app', ['active' => 'work'])

@section('content')
<div class="row">
    <div class="col-lg-12">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page"><a href="{{url('home')}}">Dashboard</a></li>
            <li class="breadcrumb-item" aria-current="page"><a href="{{url('work')}}">Trabajos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Crear</li>
          </ol>
        </nav>
        <div class="card">
            <div class="header">
                <h4 class="title">Crear trabajo</h4>
            </div>
            <div class="content">
                <div class="row">
                    <div class="col-xs-12">
                        <form class="form-horizontal" action="{{route('work.store')}}" method="post">
                            @csrf
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Fecha</label>
                                    <input type="date" class="form-control" name="date" value="{{Carbon\Carbon::now()->format('Y-m-d')}}" autofocus="">
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Empresa</label>
                                    <select name="business_id" class="form-control">
                                    	@foreach(Auth::user()->businesses as $business)
											<option value="{{$business->id}}">{{$business->name}}</option>
                                    	@endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Descripción</label>
                                    <input type="text" class="form-control" placeholder="Descripción" name="description">
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Estado</label>
                                    <select name="status" class="form-control">
                                        <option value="pending">Pendiente</option>
                                        <option value="payment">Págo</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Costo</label>
                                    <input type="text" class="form-control" placeholder="Costo" name="cost">
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Gano</label>
                                    <input type="text" class="form-control" placeholder="Gano" name="gain">
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Guardo</label>
                                    <input type="text" class="form-control" placeholder="Guardo" name="saved">
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Vence</label>
                                    <input type="date" class="form-control" placeholder="Vence" name="expires">
                                </div>
                            </div>
                            <div class="col-xs-12">
                                <button type="submit" class="btn btn-info btn-fill pull-right">
                                    <i class="pe-7s-diskette"></i>
                                    Guardar
                                </button>
                            </div>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/work/edit.blade.php
@extends('layouts.app', ['active' => 'work'])

@section('content')
<div class="row">
    <div class="col-lg-12">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page"><a href="{{url('home')}}">Dashboard</a></li>
            <li class="breadcrumb-item" aria-current="page"><a href="{{url('work')}}">Trabajos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Editar</li>
          </ol>
        </nav>
        <div class="card">
            <div class="header">
                <h4 class="title">Editar trabajo</h4>
            </div>
            <div class="content">
                <div class="row">
                    <div class="col-xs-12">
                        <form class="form-horizontal" action="{{route('work.update', $work->id)}}" method="post">
                            @csrf
                            <input type="hidden" name="_method" value="PATCH">
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Fecha</label>
                                    <input type="date" class="form-control" name="date" value="{{$work->date->format('Y-m-d')}}">
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Empresa</label>
                                    <select name="business_id" class="form-control">
                                    	@foreach(Auth::user()->businesses as $business)
											@if($business->id == $work->business_id)
												<option value="{{$business->id}}" selected>{{$business->name}}</option>
											@else
												<option value="{{$business->id}}">{{$business->name}}</option>
											@endif
                                    	@endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Descripción</label>
                                    <input type="text" class="form-control" value="{{$work->description}}" name="description">
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Estado</label>
                                    <select name="status" class="form-control">
                                        @if($work->status == "pending")
                                            <option value="pending" selected="">Pendiente</option>
                                            <option value="payment">Págo</option>
                                        @else
                                            <option value="pending">Pendiente</option>
                                            <option value="payment" selected="">Págo</option>
                                        @endif
                                    </select>
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Costo</label>
                                    <input type="text" class="form-control" value="{{$work->cost}}" name="cost">
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Gano</label>
                                    <input type="text" class="form-control" value="{{$work->gain}}" name="gain">
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Guardo</label>
                                    <input type="text" class="form-control" value="{{$work->saved}}" name="saved">
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Vence</label>
                                    <input type="date" class="form-control" value="{{$work->expires}}" name="expires">
                                </div>
                            </div>
                            <div class="col-xs-12">
                                <button type="submit" class="btn btn-info btn-fill pull-right">
                                    <i class="pe-7s-diskette"></i>
                                    Guardar
                                </button>
                            </div>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/work/index.blade.php
@extends('layouts.app', ['active' => 'work'])

@section('css')
    <style>
        .table th:hover
        {
           cursor: pointer; 
        }
    </style>
@endsection

@section('content')
<div class="row">
    <div class="col-lg-12">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">Trabajos</li>
          </ol>
        </nav>
        <div class="card">
            <div class="header">
                <div class="row">
                    <div class="col-xs-6">
                        <h4 class="title">Trabajos</h4>
                        <p class="category">Trabajos registradas</p>
                    </div>
                    <div class="col-xs-6 text-right">
                    	<a href="{{url('work/create')}}" class="btn btn-success btn-fill">
                            <i class="fa fa-plus"></i>
                            Agregar
                        </a>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="table table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                              <th scope="col">Fecha <small><i class="fa fa-sort"></i></small></th>
                              <th scope="col">Empresa <small><i class="fa fa-sort"></i></small></th>
                              <th scope="col">Descripción <small><i class="fa fa-sort"></i></small></th>
                              <th scope="col">Costo <small><i class="fa fa-sort"></i></small></th>
                              <th scope="col">Gano <small><i class="fa fa-sort"></i></small></th>
                              <th scope="col">Guardo <small><i class="fa fa-sort"></i></small></th>
                              <th scope="col">Estado <small><i class="fa fa-sort"></i></small></th>
                              <th scope="col">Vence <small><i class="fa fa-sort"></i></small></th>
                              <th>Editar</th>
                              <th>Eliminar</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(Auth::user()->works->sortByDesc('date') as $work)
                                <tr>
                                    <td>{{$work->date->format('d/m/Y')}}</td>
                                    <td>{{$work->business->name}}</td>
                                    <td>{{$work->description}}</td>
                                    <td>@if($work->cost == null) -- @else $ {{$work->cost}} @endif</td>
                                    <td>@if($work->gain == null) -- @else $ {{$work->gain}} @endif</td>
                                    <td>@if($work->saved == null) -- @else $ {{$work->saved}} @endif</td>
                                    <td>@if($work->status == 'pending') Pendiente @else Págo @endif</td>
                                    <td>@if($work->expires == null) -- @else {{$work->expires->format('d/m/Y')}} @endif</td>
                                    <td>
                                        <a href="{{route('work.edit', $work->id)}}" class="btn btn-primary btn-fill">
                                            <i class="fa fa-edit"></i>
                                            Editar
                                        </a>
                                    </td>
                                    <td>
                                        <form action="{{ url('work', $work->id)}}" method="POST">
                                            @csrf
                                            <input type='hidden' name='_method' value='DELETE'>
                                            <button class="btn btn-danger btn-fill">
                                                <i class="fa fa-trash"></i>
                                                Eliminar
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script>
       $(document).ready(function(){ 
            $("#table").tablesorter(); 
        }); 
    </script>
@endsection