routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PeopleController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\NoteController;
use App\Http\Controllers\BusinessController;
use App\Http\Controllers\WorkController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\PasswordController;
use App\Http\Controllers\ConversationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return view('welcome');
});

Route::get('/'                          , [HomeController::class, 'index'])->middleware('auth');
Route::get('/home'                      , [HomeController::class, 'index'])->middleware('auth');

Route::resource('people'                , PeopleController::class)->middleware('auth');
Route::resource('category'              , CategoryController::class)->middleware('auth');
Route::resource('note'                  , NoteController::class)->middleware('auth');
Route::resource('business'              , BusinessController::class)->middleware('auth');
Route::resource('work'                  , WorkController::class)->middleware('auth');
Route::resource('support'               , SupportController::class)->middleware('auth');
Route::resource('password'              , PasswordController::class)->middleware('auth');
Route::resource('conversation'          , ConversationController::class)->middleware('auth');
Route::get('conversation/search/{id}'   , [ConversationController::class, 'search'])->middleware('auth');

Route::post('search'                    , [HomeController::class, 'search'])->middleware('auth');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function peoples()
    {
    	return $this->hasMany('App\Models\People');
    }

    public function user()
    {
    	return $this->belongsTo('App\Models\User');
    }

    public function business()
    {
    	return $this->belongsTo('App\Models\Business');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Category;
use Auth;

class CategoryController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('category.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category               = new Category();
        $category->title        = $request->title;
        $category->description  = $request->description;
        $category->user_id      = Auth::id();
        $category->save();

        return view('category.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::find($id);
        $peoples  = $category->peoples()->paginate(10);

        return view('category.show', compact('category', 'peoples'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);

        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category               = Category::find($id);
        $category->title        = $request->title;
        $category->description  = $request->description;
        $category->save();

        return view('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $category->delate();

        return view("category.index");
    }
}

resources/views/category/create.blade.php
@extends('layouts.app', ['active' => 'category'])

@section('content')
<div class="row">
    <div class="col-lg-12">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page"><a href="{{url('home')}}">Dashboard</a></li>
            <li class="breadcrumb-item" aria-current="page"><a href="{{url('category')}}">Categorias</a></li>
            <li class="breadcrumb-item active" aria-current="page">Crear</li>
          </ol>
        </nav>
        <div class="card">
            <div class="header">
                <h4 class="title">Crear categoria</h4>
            </div>
            <div class="content">
                <div class="row">
                    <div class="col-xs-12">
                        <form class="form-horizontal" action="{{route('category.store')}}" method="post">
                            @csrf
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Titulo</label>
                                    <input type="text" class="form-control" placeholder="Titulo" name="title">
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Descripción</label>
                                    <input type="text" class="form-control" placeholder="Descripción" name="description">
                                </div>
                            </div>
                            <div class="col-xs-12">
                                <button type="submit" class="btn btn-info btn-fill pull-right">
                                    <i class="pe-7s-diskette"></i>
                                    Guardar
                                </button>
                            </div>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.app', ['active' => 'category'])

@section('content')
<div class="row">
    <div class="col-lg-12">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page"><a href="{{url('home')}}">Dashboard</a></li>
            <li class="breadcrumb-item" aria-current="page"><a href="{{url('category')}}">Categorias</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{$category->title}}</li>
          </ol>
        </nav>
        <div class="card">
            <div class="header">
                <h4 class="title">Editar categoria</h4>
            </div>
            <div class="content">
                <div class="row">
                    <div class="col-xs-12">
                        <form class="form-horizontal" action="{{route('category.update', $category->id)}}" method="post">
                            @csrf
                            <input type="hidden" name="_method" value="PATCH">
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Titulo</label>
                                    <input type="text" class="form-control" placeholder="Titulo" name="title" value="{{$category->title}}">
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Descripción</label>
                                    <input type="text" class="form-control" placeholder="Descripción" name="description" value="{{$category->description}}">
                                </div>
                            </div>
                            <div class="col-xs-12">
                                <button type="submit" class="btn btn-info btn-fill pull-right">
                                    <i class="pe-7s-diskette"></i>
                                    Guardar
                                </button>
                            </div>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/category/index.blade.php
@extends('layouts.app', ['active' => 'category'])

@section('content')
<div class="row">
    <div class="col-lg-12">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">Categorias</li>
          </ol>
        </nav>
        <div class="card">
            <div class="header">
                <div class="row">
                    <div class="col-xs-6">
                        <h4 class="title">Categorias</h4>
                        <p class="category">Categorias registradas</p>
                    </div>
                    <div class="col-xs-6 text-right">
                        <a href="{{url('category/create')}}" class="btn btn-success btn-fill">
                            <i class="fa fa-plus"></i>
                            Agregar
                        </a>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="table table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                              <th scope="col">Titulo</th>
                              <th scope="col">Descripción</th>
                              <th></th>
                              <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(Auth::user()->categories as $category)
                                <tr>
                                    <td>
                                        <a href="{{url('category', $category->id)}}">
                                            {{$category->title}}
                                        </a>
                                    </td>
                                    <td>{{$category->description}}</td>
                                    <td>
                                        <a href="{{route('category.edit', $category->id)}}" class="btn btn-primary btn-fill">
                                            <i class="fa fa-edit"></i>
                                            Editar
                                        </a>
                                    </td>
                                    <td>
                                        <form action="{{ url('category', $category->id)}}" method="POST">
                                            @csrf
                                            <input type='hidden' name='_method' value='DELETE'>
                                            <button class="btn btn-danger btn-fill">
                                                <i class="fa fa-trash"></i>
                                                Eliminar
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/category/show.blade.php
@extends('layouts.app', ['active' => 'category'])

@section('css')
    <style>
        .table th:hover
        {
           cursor: pointer; 
        }
    </style>
@endsection


@section('content')
<div class="row">
    <div class="col-lg-12">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page"><a href="{{url('home')}}">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{$category->title}}</li>
          </ol>
        </nav>
        <div class="card">
            <div class="header">
                <div class="row">
                    <div class="col-xs-6">
                        <h4 class="title">{{$category->title}}</h4>
                    </div>
                    <div class="col-xs-6 text-right">
                        <a href="{{url('people/create')}}" class="btn btn-success btn-fill">
                            <i class="fa fa-plus"></i>
                            Agregar
                        </a>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="table table-responsive">
                    <table id="table" class="table table-striped ">
                        <thead>
                            <tr>
                              <th scope="col">Nombre <small><i class="fa fa-sort"></i></small></th>
                              <th scope="col">Descripción <small><i class="fa fa-sort"></i></small></th>
                              <th scope="col">Email <small><i class="fa fa-sort"></i></small></th>
                              <th scope="col">Telefono <small><i class="fa fa-sort"></i></small></th>
                              <th></th>
                              <th></th>
                              <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($peoples as $people)
                                <tr>
                                    <td>
                                        <a href="{{url('people', $people->id)}}">
                                            {{$people->name}}
                                        </a>
                                    </td>
                                    <td>{{$people->description}}</td>
                                    <td><a href="mailto:{{$people->email}}">{{$people->email}}</a></td>
                                    <td>{{$people->phone}}</td>
                                    <td>
                                        <a href="{{url('people', $people->id)}}" class="btn btn-info btn-fill">
                                            <i class="fa fa-eye"></i>
                                            Ver
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{route('people.edit', $people->id)}}" class="btn btn-primary btn-fill">
                                            <fa class="fa fa-edit"></fa>
                                            Editar
                                        </a>
                                    </td>
                                    <td>
                                        <form id="delete-form-{{$people->id}}" action="{{ url('people', $people->id)}}" method="POST">
                                            @csrf
                                            <input type='hidden' name='_method' value='DELETE'>
                                            <button class="btn btn-danger btn-fill">
                                                <i class="fa fa-trash"></i>
                                                Eliminar
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="footer">
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script>
       $(document).ready(function(){ 
            $("#table").tablesorter(); 
        }); 
    </script>
@endsection