routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PeopleController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\NoteController;
use App\Http\Controllers\BusinessController;
use App\Http\Controllers\WorkController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\PasswordController;
use App\Http\Controllers\ConversationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return view('welcome');
});

Route::get('/'                          , [HomeController::class, 'index'])->middleware('auth');
Route::get('/home'                      , [HomeController::class, 'index'])->middleware('auth');

Route::resource('people'                , PeopleController::class)->middleware('auth');
Route::resource('category'              , CategoryController::class)->middleware('auth');
Route::resource('note'                  , NoteController::class)->middleware('auth');
Route::resource('business'              , BusinessController::class)->middleware('auth');
Route::resource('work'                  , WorkController::class)->middleware('auth');
Route::resource('support'               , SupportController::class)->middleware('auth');
Route::resource('password'              , PasswordController::class)->middleware('auth');
Route::resource('conversation'          , ConversationController::class)->middleware('auth');
Route::get('conversation/search/{id}'   , [ConversationController::class, 'search'])->middleware('auth');

Route::post('search'                    , [HomeController::class, 'search'])->middleware('auth');

app/Models/Support.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Support extends Model
{
    public function user()
    {
    	return $this->belongsTo('App\Models\User');
    }

    public function business()
    {
    	return $this->belongsTo('App\Models\Business');
    }
}

app/Http/Controllers/SupportController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Support;
use Auth;

class SupportController extends Controller
{
    private $path = "support.";

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view($this->path."index");
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->path."create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $support                = new Support();
        $support->number        = $request->number;
        $support->type          = $request->type;
        $support->description   = $request->description;
        $support->business_id   = $request->business_id;
        $support->user_id       = Auth::user()->id;

        $support->save();

        return redirect('support');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $support = Support::find($id);
        return view($this->path."edit", compact('support'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $support                = Support::find($id);
        $support->number        = $request->number;
        $support->type          = $request->type;
        $support->description   = $request->description;
        $support->business_id   = $request->business_id;

        $support->save();

        return redirect('support');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $support = Support::find($id);
        $support->delete();

        return redirect('support');
    }
}

resources/views/support/create.blade.php
@extends('layouts.app', ['active' => 'support'])

@section('content')
<div class="row">
    <div class="col-lg-12">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page"><a href="{{url('home')}}">Dashboard</a></li>
            <li class="breadcrumb-item" aria-current="page"><a href="{{url('business')}}">Equipos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Crear</li>
          </ol>
        </nav>
        <div class="card">
            <div class="header">
                <h4 class="title">Crear equipo</h4>
            </div>
            <div class="content">
                <div class="row">
                    <div class="col-xs-12">
                        <form class="form-horizontal" action="{{route('support.store')}}" method="post">
                            @csrf
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Numero</label>
                                    <input type="text" class="form-control" placeholder="Numero" name="number">
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Tipo</label>
                                    <input type="text" class="form-control" placeholder="Tipo" name="type">
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Descripción</label>
                                    <input type="text" class="form-control" placeholder="Descripción" name="description">
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Empresa</label>
                                    <select name="business_id" class="form-control">
                                        @foreach(Auth::user()->businesses as $business)
                                            <option value="{{$business->id}}">{{$business->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-xs-12">
                                <button type="submit" class="btn btn-info btn-fill pull-right">
                                    <i class="pe-7s-diskette"></i>
                                    Guardar
                                </button>
                            </div>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/support/edit.blade.php
@extends('layouts.app', ['active' => 'support'])

@section('content')
<div class="row">
    <div class="col-lg-12">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page"><a href="{{url('home')}}">Dashboard</a></li>
            <li class="breadcrumb-item" aria-current="page"><a href="{{url('business')}}">Equipos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Editar</li>
          </ol>
        </nav>
        <div class="card">
            <div class="header">
                <h4 class="title">Editar equipo</h4>
            </div>
            <div class="content">
                <div class="row">
                    <div class="col-xs-12">
                        <form class="form-horizontal" action="{{route('support.update', $support->id)}}" method="post">
                            @csrf
                            <input type="hidden" name="_method" value="PATCH">
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Numero</label>
                                    <input type="text" class="form-control" value="{{$support->number}}" name="number">
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Tipo</label>
                                    <input type="text" class="form-control" value="{{$support->type}}" name="type">
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Descripción</label>
                                    <input type="text" class="form-control" value="{{$support->description}}" name="description">
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label>Empresa</label>
                                    <select name="business_id" class="form-control">
                                    	@foreach(Auth::user()->businesses as $business)
											@if($business->id == $support->business_id)
												<option value="{{$business->id}}" selected>{{$business->name}}</option>
											@else
												<option value="{{$business->id}}">{{$business->name}}</option>
											@endif
                                    	@endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-xs-12">
                                <button type="submit" class="btn btn-info btn-fill pull-right">
                                    <i class="pe-7s-diskette"></i>
                                    Guardar
                                </button>
                            </div>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/support/index.blade.php
@extends('layouts.app', ['active' => 'support'])

@section('content')
<div class="row">
    <div class="col-lg-12">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">Equipos</li>
          </ol>
        </nav>
        <div class="card">
            <div class="header">
                <div class="row">
                    <div class="col-xs-6">
                        <h4 class="title">Equipos</h4>
                        <p class="category">Equipos registrados</p>
                    </div>
                    <div class="col-xs-6 text-right">
                        <a href="{{url('support/create')}}" class="btn btn-success btn-fill">
                            <i class="fa fa-plus"></i>
                            Agregar
                        </a>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="table table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                              <th scope="col">Numero</th>
                              <th scope="col">Tipo</th>
                              <th scope="col">Descripción</th>
                              <th scope="col">Empresa</th>
                              <th scope="col">Editar</th>
                              <th scope="col">Eliminar</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(Auth::user()->supports as $support)
                                <tr>
                                    <td># {{$support->number}}</td>
                                    <td>{{$support->type}}</td>
                                    <td>{{$support->description}}</td>
                                    <td><a href="{{url('business', $support->business_id)}}">{{$support->business->name}}</a></td>
                                    <td>
                                        <a href="{{route('support.edit', $support->id)}}" class="btn btn-primary btn-fill">
                                            <i class="fa fa-edit"></i>
                                            Editar
                                        </a>
                                    </td>
                                    <td>
                                        <form action="{{ url('support', $support->id)}}" method="POST">
                                            @csrf
                                            <input type='hidden' name='_method' value='DELETE'>
                                            <button class="btn btn-danger btn-fill">
                                                <i class="fa fa-trash"></i>
                                                Eliminar
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection